### ISSUE TITLE
glance image create failed, stuck in queued status

### ISSUE THREAD

**Issue by jerryz1982** [kidchang/openstack-ansible#3]
| 6c000758-1580-4ebc-ba6d-5dc40fad700f | cirros-0.3.3-x86_64-disk.img | qcow2       | bare             | 13200896 | queued |

2015-03-03 12:25:44.708 17006 ERROR glance.registry.api.v1.images [f398b6f3-fb41-452c-b122-b6e6f371c2b1 06fbf2aaf5ed4609ba57df47f53cd965 30af8b5eb252403ea54acb586ddaacc7 - - -] Unable to update image 6c000758-1580-4ebc-ba6d-5dc40fad700f
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images Traceback (most recent call last):
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/glance/registry/api/v1/images.py", line 478, in update
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     from_state=from_state)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/glance/db/sqlalchemy/api.py", line 135, in image_update
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     from_state=from_state)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/retrying.py", line 68, in wrapped_f
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     return Retrying(_dargs, *_dkw).call(f, _args, *_kw)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/retrying.py", line 223, in call
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     return attempt.get(self._wrap_exception)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/retrying.py", line 261, in get
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     six.reraise(self.value[0], self.value[1], self.value[2])
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/retrying.py", line 217, in call
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     attempt = Attempt(fn(_args, *_kwargs), attempt_number, False)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/glance/db/sqlalchemy/api.py", line 694, in _image_update
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     image_ref = _image_get(context, image_id, session=session)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/glance/db/sqlalchemy/api.py", line 226, in _image_get
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     image = query.one()
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2369, in one
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     ret = list(self)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2412, in __iter__
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     return self._execute_and_instances(context)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2427, in _execute_and_instances
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     result = conn.execute(querycontext.statement, self._params)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     return meth(self, multiparams, params)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     return connection._execute_clauseelement(self, multiparams, params)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     compiled_sql, distilled_params
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     context)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1156, in _handle_dbapi_exception
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     util.raise_from_cause(newraise, exc_info)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     reraise(type(exception), exception, tb=exc_tb)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     context)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     cursor.execute(statement, parameters)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     self.errorhandler(self, exc, value)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images     raise errorclass, errorvalue
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images DBConnectionError: (OperationalError) (2006, 'MySQL server has gone away') 'SELECT images.created_at AS images_created_at, images.updated_at AS images_updated_at, images.deleted_at AS images_deleted_at, images.deleted AS images_deleted, images.id AS images_id, images.name AS images_name, images.disk_format AS images_disk_format, images.container_format AS images_container_format, images.size AS images_size, images.virtual_size AS images_virtual_size, images.status AS images_status, images.is_public AS images_is_public, images.checksum AS images_checksum, images.min_disk AS images_min_disk, images.min_ram AS images_min_ram, images.owner AS images_owner, images.protected AS images_protected, image_locations_1.created_at AS image_locations_1_created_at, image_locations_1.updated_at AS image_locations_1_updated_at, image_locations_1.deleted_at AS image_locations_1_deleted_at, image_locations_1.deleted AS image_locations_1_deleted, image_locations_1.id AS image_locations_1_id, image_locations_1.image_id AS image_locations_1_image_id, image_locations_1.value AS image_locations_1_value, image_locations_1.meta_data AS image_locations_1_meta_data, image_locations_1.status AS image_locations_1_status, image_properties_1.created_at AS image_properties_1_created_at, image_properties_1.updated_at AS image_properties_1_updated_at, image_properties_1.deleted_at AS image_properties_1_deleted_at, image_properties_1.deleted AS image_properties_1_deleted, image_properties_1.id AS image_properties_1_id, image_properties_1.image_id AS image_properties_1_image_id, image_properties_1.name AS image_properties_1_name, image_properties_1.value AS image_properties_1_value \nFROM images LEFT OUTER JOIN image_locations AS image_locations_1 ON images.id = image_locations_1.image_id LEFT OUTER JOIN image_properties AS image_properties_1 ON images.id = image_properties_1.image_id \nWHERE images.id = %s' ('6c000758-1580-4ebc-ba6d-5dc40fad700f',)
2015-03-03 12:25:44.708 17006 TRACE glance.registry.api.v1.images

**Comment by jerryz1982** [comment]
There was a restart of mysql at this time.
Version: '5.5.41-0ubuntu0.14.04.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Ubuntu)
150303 12:25:44 [Note] /usr/sbin/mysqld: Normal shutdown

150303 12:25:44 [Note] Event Scheduler: Purging the queue. 0 events
150303 12:25:46 [Warning] /usr/sbin/mysqld: Forcing close of thread 61  user: 'nova'

150303 12:25:46 [Warning] /usr/sbin/mysqld: Forcing close of thread 59  user: 'nova'

150303 12:25:46 [Warning] /usr/sbin/mysqld: Forcing close of thread 56  user: 'keystone'

150303 12:25:46 [Warning] /usr/sbin/mysqld: Forcing close of thread 55  user: 'keystone'

150303 12:25:46 [Warning] /usr/sbin/mysqld: Forcing close of thread 52  user: 'cinder'

150303 12:25:46  InnoDB: Starting shutdown...
150303 12:25:47  InnoDB: Waiting for 162 pages to be flushed
150303 12:25:48  InnoDB: Shutdown completed; log sequence number 6294563
150303 12:25:48 [Note] /usr/sbin/mysqld: Shutdown complete

150303 12:25:48 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
150303 12:25:48 [Note] Plugin 'FEDERATED' is disabled.
150303 12:25:48 InnoDB: The InnoDB memory heap is disabled
150303 12:25:48 InnoDB: Mutexes and rw_locks use GCC atomic builtins
150303 12:25:48 InnoDB: Compressed tables use zlib 1.2.8
150303 12:25:48 InnoDB: Using Linux native AIO
150303 12:25:48 InnoDB: Initializing buffer pool, size = 128.0M
                                                                      150303 12:25:48 InnoDB: Completed initialization of buffer pool
150303 12:25:48 InnoDB: highest supported file format is Barracuda.
150303 12:25:48  InnoDB: Waiting for the background threads to start
150303 12:25:49 InnoDB: 5.5.41 started; log sequence number 6294563
150303 12:25:49 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
150303 12:25:49 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
150303 12:25:49 [Note] Server socket created on IP: '0.0.0.0'.
150303 12:25:49 [Note] Event Scheduler: Loaded 0 events
150303 12:25:49 [Note] /usr/sbin/mysqld: ready for connections.
Version: '5.5.41-0ubuntu0.14.04.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Ubuntu)

**Comment by jerryz1982** [comment]
Mar  3 12:25:38 vagrant-ubuntu-trusty-64 ansible-command: Invoked with executable=None shell=True args=/opt/image_upload.sh && touch image_upload_completed removes=None creates=image_upload_completed chdir=None
Mar  3 12:25:44 vagrant-ubuntu-trusty-64 ansible-service: Invoked with name=mysql pattern=None enabled=None state=restarted sleep=None arguments= runlevel=default

**Comment by kidchang** [comment]
Was this error thrown by Ansible? I had the same errors too, which was due to the glance image create/upload action before 9292 being brought up. I added a line in Ansible to prevent uploading until port is up. Don't know if this is the case.

**Comment by jerryz1982** [comment]
9292 was up. glance api worked. from the first log, it was db that was down.
second comment is mysql.log, third is syslog.

**Comment by kidchang** [comment]
I encountered "mysqldb has gone away" errors too, but failed re-produce it. Did your commit fix the issue? Would you be able to locate the bug?

**Comment by jerryz1982** [comment]
i suspect db restart was notified and executed at the end, immediately after glance role was finished.
syslog shows that the db was restarted by ansible on purpose, not by accident. weird that you couldn't reproduce it.
my commit won't fix this issue. i only saw in db role task there was a db restart, somehow it got executed in the end as well.

**Comment by kidchang** [comment]
This is because "notify" commands will be and will only be executed during end of each play run and direct commands for actions will be executed immediately, and I think I placed both "notify" and "shell" for mysql db restart, which is probably why db has this problem.

I will look into it.

**Comment by jerryz1982** [comment]
the problem is that glance image-create from remote source is an async action, and after it returned true, restart mysql will be executed, which is required as it subscribes to my.cnf.
we could download cirros image, and create image from the file instead of url, also there had better be a delay after glance image-create.

**Comment by kidchang** [comment]
There is a "wait_for: port=9292 delay=5" in the action before running image upload. I am adding another delay in the sh script.

**Comment by jerryz1982** [comment]
That won't do it. It is the db restart after asynchronous image create causing the issue.
I have fix it by creating from local file, which is synchronous. 

Best regards!
Jerry

**Comment by kidchang** [comment]
OK I may revert that change I made to image_upload.sh later, it would only sleep for 10 sec before uploading. I ran a test earlier today and still it complained that "No Valid host was found", but this time it's different that I traversed all nova logs but found no errors. Could you help look at that, too?

**Comment by neerajvayu** [comment]
I have faced same issue and i tried to upload image from file/ISo format but that also not worked and status shown was killed
